Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "whisky")
Ingredient.create(name: "rhum")
Ingredient.create(name: "perrier")
Ingredient.create(name: "sausage")
